### ISSUE TITLE
Disable Java censor for project

### ISSUE THREAD

**Issue by dbarwacz** [schlan/java-censor#5]
Hey! 
I have to browse through 3rd party code obfuscated with java-censor. 
The code itself is not even mimified, so I have absolutely no problems understanding it. IDE notices differences between sources and .class contents, so I end up clicking 'show .class contents' every time I open library class. Can this behaviour be disabled somehow? 

Although to be honest, I have to say, The Room references made me laugh a lot. It's just I'd rather avoid clicking 'show class' now and be more productive

**Comment by schlan** [comment]
Hey, sorry for the very, very later answer. The whole purpose of this plugin is to enable closed source projects to publish a source artefact to a maven repository. This is necessary because IDEs like AndroidStudio rely on a source artefact to showing Javadocs when integrating.
